<?php
/**
 * This code was originally the following:
 * 
 * class Galaxy {
 *   private host;
 *   private port;
 * 
 *   public __construct() {
 *   }
 * 
 *   public getURL() {
 *   }
 * }
 * 
 * I was getting errors earlier and I hope this is better,
 * I'll ask Stephen about it to make sure 
 * 
 * @author cwytko @timestamp Aug 31, 2015 5:02:35 PM
 *
 */
class Galaxy {
  private $host;
  private $port;
  
  public function __construct() {
  }
  
  // This needs to be defined similar to the class method like php's
  // HttpRequest::getUrl() 
  public function getURL() {
  	
  }
}