<?php

   $config = array(
    "host"=> 'localhost',
    "user" => 'brotato',
    "email" => 'cgpwytko@gmail.com',
    "pass" => 'potato15',
    "port" => '8080',
    "api_key" => 'd2f6e907674e916cbfcc8fb0865e52f5',
);

//   $config = array(
//     "host" =>  'localhost',
//     "user" =>  'bob',
//     "email" => 'bob@gmail.com',
//     "pass" =>  'password',
//     "port" =>  '8080',
//     "api_key" =>'e61587135b254f99e4d042f268918f69',
//   );




/*
$config = array(
  "host" =>  'localhost',
  "user" =>  'spficklin',
  "email" =>  'spficklin@gmail.com',
  "pass" =>  'testing123',
  "port" =>  '8090',
  "api_key" =>  'afcbaa548c3af9cd0478d1c8543a55da',
);
 */