<?php

$config_brian = array(
  "host" =>  'localhost',
  "user" =>  'bob@gmail.com',
  "pass" =>  'password',
  "port" =>  '8080',
  "api_key" =>  '7ef496ca9fee28566c59bc2c9d8bddae',
  "username"=> "bob",
  "user_id"=> "f2db41e1fa331b3e",	
		
);

$config = array(
  "host"=> 'localhost',		
  "user" =>  'cgpwytko@gmail.com',
  "pass" =>  'potato15',
  "port" =>  '8080',
  "api_key" =>  '6ed6cab9786251ba8f82eaf9bdc8e0b0',
 );

// $config = array(
//   "host" =>  'localhost',
//   "user" =>  'spficklin@gmail.com',
//   "pass" =>  'testing123',
//   "port" =>  '8090',
//   "api_key" =>  'afcbaa548c3af9cd0478d1c8543a55da',
// );
